### ISSUE TITLE
zsh: unknown file attribute: 1

### ISSUE THREAD

**Issue by swyoon** [fbickfordsmith/epig#1]
Dear Freddie,

First of all, thank you for your work. I am quite interested in active learning and also reached out to you via twitter :)

I'm trying to follow the instruction in the `readme.md`. So after setting up the environment, I tried a line in `two_bells.sh`

```bash
python main.py --multirun rng.seed=range(100) data=two_bells/100k model=gaussian_process trainer=gaussian_process experiment_name=two_bells_100k acquisition.objective=bald
```

Then I got:
```
zsh: unknown file attribute: 1
```

I was able to run the command if I remove `--multirun rng.seed=range(100)` part.

Would you take a look into this command issue?

Best,
Sangwoong.

**Comment by fbickfordsmith** [comment]
Hi Sangwoong,

I’m so sorry I missed this! For some reason I didn’t receive a notification from GitHub when you opened the issue, and the issues indicator only caught my eye today when I was taking a look at the repo.

Thanks for flagging this problem. It didn’t show up in the Slurm workflow I was using to run experiments, but I can reproduce the problem at the command line now. You’re right that the culprit is the `rng.seed=range(100)` part. Using quotation marks around `range(100)` should solve it:

```bash
python main.py --multirun rng.seed="range(100)" data=two_bells/100k model=gaussian_process trainer=gaussian_process experiment_name=two_bells_100k acquisition.objective=bald
```

I've applied this change to the jobs files in this branch: https://github.com/fbickfordsmith/epig/tree/fix-job-commands.

Freddie

**Comment by swyoon** [comment]
Dear Freddie, thank you for your reply! I managed to run your script back then, so no worries.
